[project]
name = "my-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "arize-phoenix-otel>=0.8.0",
    "arize-phoenix>=8.3.0",
    "litellm>=1.61.15",
    "openinference-instrumentation-litellm>=0.1.11",
]
